default:
  http_metas:
    content-type: text/html

  metas:
    title:        cllajinet
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:        index, follow

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout
