propel:
  post:
    id:          ~
    title:       varchar(255)
    excerpt:     longvarchar
    body:        longvarchar
    created_at:  ~
  comment:
    id:          ~
    post_id:     ~
    author:      varchar(255)
    email:       varchar(255)
    body:        longvarchar
    created_at:  ~
